### ISSUE TITLE
Example Data from python script.

### ISSUE THREAD

**Issue by Flirina** [thomluther/anker-solix-api#1]
Hi tholu,
as requested there are some sample data from the export script.

SETUP:
HM 1600 Inverter
2x 410w panels.
1x solarbank e1600

[ExampleTheNotoriousFlow.zip](https://github.com/thomluther/anker-solix-api/files/14162258/ExampleTheNotoriousFlow.zip)

regards
florian

**Comment by thomluther** [comment]
@Flirina, thanks for the data.
Will have a look to it and see if there is additional content to be extracted for the API site and device information.
It would be great if we get data extracts from a multiple Solarbank setup or multiple site setup, since that may have an impact to the API data gathering behavior.
Of course, data from Anker Inverter or power stations would be nice too.
