### ISSUE TITLE
Energy Plan (schedule): possibility to extract current settings and upload a desired plan?

### ISSUE THREAD

**Issue by HakunaMatata47** [thomluther/anker-solix-api#146]
Hi. Thanks for this API.

I found the file   anker-solix-api/blob/main/examples/SB1_Dual_Old_schedule_NoEnergy/api_devices.json
and wonder if it is possible to somehow extract the current energy plan?
and more important upload a new energy plan.

Maybe with anker-solix-api/api/schedule.py 

But I frankly have no idea how to do that but that example file looks like it should be possible in general with this API.
My idea was to have some energy plans stored for certain scenarios and to run a python script to decide which one to upload.

So far I use   anker-solix-api/test_api.py   to extract battery soc information
So using an account to authenticate and getting device information principally works for me.

Many thanks for a hint how to use it.

**Comment by thomluther** [comment]
If you have Home Assistnant, I recommend to use the HA integration.
Otherwise, there are helper methods to modify and update the schedule for the solarbank based on parameters.
[set_home_load](https://github.com/thomluther/anker-solix-api/blob/3c991eb037d0dd6389e50beb024fd58bc109fc94/api/schedule.py#L251C11-L251C24)
[set_sb2_home_load ](https://github.com/thomluther/anker-solix-api/blob/3c991eb037d0dd6389e50beb024fd58bc109fc94/api/schedule.py#L1064
)
If you want to apply a whole schedule object directly, you can see how that is done with the set_device_parm method at the end of the helper methods.
